spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_APP_USERNAME}
    password: ${MYSQL_APP_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

server:
  port: ${HTTP_LISTEN_PORT}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace

grpc:
  enable-reflection: true