-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 12:37:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema itemae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `screen_name` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `location` VARCHAR(191) NOT NULL,
  `url` VARCHAR(8190) NOT NULL,
  `born_on` DATE NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `screen_name_UNIQUE` ON `users` (`screen_name`);


-- -----------------------------------------------------
-- Table `tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweets` (
  `id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(8) UNSIGNED NOT NULL,
  `text` VARCHAR(140) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tweets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tweets_users1_idx` ON `tweets` (`user_id`);


-- -----------------------------------------------------
-- Table `retweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retweets` (
  `user_id` BIGINT(8) UNSIGNED NOT NULL,
  `tweet_id` BIGINT(8) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `tweet_id`),
  CONSTRAINT `fk_retweets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retweets_tweets1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_retweets_tweets1_idx` ON `retweets` (`tweet_id`);


-- -----------------------------------------------------
-- Table `favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `favorites` (
  `user_id` BIGINT(8) UNSIGNED NOT NULL,
  `tweet_id` BIGINT(8) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `tweet_id`),
  CONSTRAINT `fk_likes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_tweets1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_likes_tweets1_idx` ON `favorites` (`tweet_id`);


-- -----------------------------------------------------
-- Table `friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friends` (
  `following_user_id` BIGINT(8) UNSIGNED NOT NULL,
  `followed_user_id` BIGINT(8) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`following_user_id`, `followed_user_id`),
  CONSTRAINT `fk_friends_users1`
    FOREIGN KEY (`following_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_users2`
    FOREIGN KEY (`followed_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_friends_users2_idx` ON `friends` (`followed_user_id`);


-- -----------------------------------------------------
-- Table `user_authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authorities` (
  `user_id` BIGINT(8) UNSIGNED NOT NULL,
  `firebase_uid` VARCHAR(191) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_authorities_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `firebase_uid_UNIQUE` ON `user_authorities` (`firebase_uid`);


-- -----------------------------------------------------
-- Table `user_notification_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_notification_tokens` (
  `user_id` BIGINT(8) UNSIGNED NOT NULL,
  `fcm_token` VARCHAR(191) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_notification_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_user_notification_tokens_users1_idx` ON `user_notification_tokens` (`user_id`);


-- -----------------------------------------------------
-- Table `notification_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notification_types` (
  `name` VARCHAR(191) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` BIGINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_user_id` BIGINT(8) UNSIGNED NOT NULL,
  `receiver_user_id` BIGINT(8) UNSIGNED NOT NULL,
  `notification_type_name` VARCHAR(191) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`receiver_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_notification_types1`
    FOREIGN KEY (`notification_type_name`)
    REFERENCES `notification_types` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_users2`
    FOREIGN KEY (`sender_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_notifications_users1_idx` ON `notifications` (`receiver_user_id`);

CREATE INDEX `fk_notifications_notification_types1_idx` ON `notifications` (`notification_type_name`);

CREATE INDEX `fk_notifications_users2_idx` ON `notifications` (`sender_user_id`);


-- -----------------------------------------------------
-- Table `notification_tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notification_tweets` (
  `notification_id` BIGINT(8) UNSIGNED NOT NULL,
  `tweet_id` BIGINT(8) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  CONSTRAINT `fk_notification_tweets_tweets1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notification_tweets_notifications1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `notifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_notification_tweets_tweets1_idx` ON `notification_tweets` (`tweet_id`);



